name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Unrar
        run: sudo apt-get update && sudo apt-get install -y unrar

      - name: Force Fix Project Structure
        run: |
          # فك ضغط الملف
          unrar x app.rar || true
          
          # البحث عن ملف gradlew في أي مكان ونقله للواجهة الرئيسية
          find . -name "gradlew" -exec cp {} . \;
          find . -name "settings.gradle.kts" -exec cp {} . \;
          find . -name "build.gradle.kts" -exec cp {} . \;
          find . -name "gradle" -type d -exec cp -r {} . \;
          
          # التأكد من وجود ملف settings إذا فقدناه
          if [ ! -f "settings.gradle.kts" ]; then
            echo "include(':app')" > settings.gradle.kts
          fi
          
          chmod +x gradlew

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build APK
        run: ./gradlew assembleDebug --no-daemon
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: snake-game-final
          path: "**/build/outputs/apk/debug/*.apk"
